# Generated by Django 3.1.3 on 2020-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='execution_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
