# Generated by Django 3.1.3 on 2020-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20201121_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collections',
            field=models.ManyToManyField(through='tweet.PostCollection', to='tweet.Collection'),
        ),
        migrations.AlterField(
            model_name='postcollection',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcollection',
            name='lastPostedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
